### ISSUE TITLE
docker run or nvidia-docker run 

### ISSUE THREAD

**Issue by Tingelam** [tanjasper/ug2_2020_challenge2_devkit#1]
- scripts in `sample_evaluation/challenge2-3/evaluate_challenge2-3.sh ` using `docker run` which can not get gpus_device  for inference.

- Should it be replaced with `nvidia-docker run`?

**Comment by tanjasper** [comment]
Yes, you are correct, thank you for catching that. Depending on your Docker version, it should either be replaced with "nvidia-docker run" or the "--gpus" flag should be set. Our final evaluation does have it set correctly and will allow your submission to use one GPU. Sorry for not updating it here.
